MyEventWorld/accounts/urls.py
from django.urls import path, include
from MyEventWorld.accounts.views import (
    UsersList,
    UserCreate,
    UserLogin,
    UserLogout,
    UserDetails,
    UserProfile,
    UserProfileEdit,
    UserProfileDelete,
    UserPasswordReset,
    UserPasswordResetDone,
    UserPasswordConfirmation,
    UserPasswordResetComplete,
)

urlpatterns = (
    path("", UsersList.as_view(), name="users-list"),
    path("register/", UserCreate.as_view(), name="register"),
    path("login/", UserLogin.as_view(), name="login"),
    path("logout/", UserLogout.as_view(), name="logout"),
    path(
        "<str:pk>/",
        include(
            [
                path("creator/", UserDetails.as_view(), name="user-details"),
                path("profile/", UserProfile.as_view(), name="profile-details"),
                path("edit/", UserProfileEdit.as_view(), name="profile-edit"),
                path("delete/", UserProfileDelete.as_view(), name="profile-delete"),
            ]
        ),
    ),
    path(
        "reset_password/",
        UserPasswordReset.as_view(),
        name="reset_password",
    ),
    path(
        "reset_password_sent/",
        UserPasswordResetDone.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        UserPasswordConfirmation.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        UserPasswordResetComplete.as_view(),
        name="password_reset_complete",
    ),
)

from .signals import *

MyEventWorld/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("my_event_world_admins/", admin.site.urls),
    path("", include("MyEventWorld.events.urls")),
    path("users/", include("MyEventWorld.accounts.urls")),
    path("common/", include("MyEventWorld.common_stuff.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyEventWorld/accounts/models.py
import uuid

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.core.validators import (
    MinLengthValidator,
    MinValueValidator,
    MaxValueValidator,
)

from cloudinary.models import CloudinaryField

from MyEventWorld.accounts.managers import EventUserManager
from MyEventWorld.core.helpers.gender_types import Genders


class EventUser(AbstractBaseUser, PermissionsMixin):
    USERNAME_ERROR = "User with that email already exist !"

    email = models.EmailField(
        unique=True,
        null=False,
        blank=False,
        verbose_name="Email",
        error_messages={"unique": USERNAME_ERROR},
    )
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(
        default=False, null=False, blank=False, verbose_name="Staff status"
    )
    date_joined = models.DateTimeField(
        auto_now_add=True,
    )
    id = models.UUIDField(
        default=uuid.uuid4, primary_key=True, unique=True, editable=False
    )

    USERNAME_FIELD = "email"

    objects = EventUserManager()


class EventProfile(models.Model):
    FIRST_NAME_MIN_LEN = 3
    FIRST_NAME_MAX_LEN = 20
    FIRST_NAME_MIN_LEN_MESSAGE = (
        f"First name must be at least {FIRST_NAME_MIN_LEN} characters long"
    )

    LAST_NAME_MIN_LEN = 3
    LAST_NAME_MAX_LEN = 30
    LAST_NAME_MIN_LEN_MESSAGE = (
        f"Last name must be at least {LAST_NAME_MIN_LEN} characters long"
    )

    LOCATION_MIN_LEN = 3
    LOCATION_MAX_LEN = 55
    LOCATION_MIN_LEN_MESSAGE = (
        f"Location must be at least {LOCATION_MIN_LEN} characters long"
    )

    ABOUT_ME_MAX_LEN = 2500

    AGE_MIN_VALUE = 18
    AGE_MAX_VALUE = 122
    AGE_VALIDATION_MESSAGE = f"Age must be between {AGE_MIN_VALUE} and {AGE_MAX_VALUE}!"

    user = models.OneToOneField(
        EventUser,
        primary_key=True,
        on_delete=models.CASCADE,
        verbose_name="User email",
    )

    profile_avatar = CloudinaryField(
        null=True,
        blank=True,
        verbose_name="Profile avatar",
    )

    first_name = models.CharField(
        max_length=FIRST_NAME_MAX_LEN,
        validators=(
            MinLengthValidator(FIRST_NAME_MIN_LEN, FIRST_NAME_MIN_LEN_MESSAGE),
        ),
        null=True,
        blank=True,
        verbose_name="First Name",
    )
    last_name = models.CharField(
        max_length=LAST_NAME_MAX_LEN,
        validators=(MinLengthValidator(LAST_NAME_MIN_LEN, LAST_NAME_MIN_LEN_MESSAGE),),
        null=True,
        blank=True,
        verbose_name="Last Name",
    )
    location = models.CharField(
        max_length=LOCATION_MAX_LEN,
        validators=(MinLengthValidator(LOCATION_MIN_LEN, LOCATION_MIN_LEN_MESSAGE),),
        null=True,
        blank=True,
        verbose_name="Location",
    )
    about_me = models.TextField(
        max_length=ABOUT_ME_MAX_LEN, null=True, blank=True, verbose_name="About me"
    )
    age = models.IntegerField(
        validators=(
            MinValueValidator(AGE_MIN_VALUE, message=AGE_VALIDATION_MESSAGE),
            MaxValueValidator(AGE_MAX_VALUE, message=AGE_VALIDATION_MESSAGE),
        ),
        null=True,
        blank=True,
        verbose_name="Age",
    )
    gender = models.CharField(
        choices=Genders.choices(),
        max_length=Genders.max_length(),
        default=Genders.Unpicked.name,
        null=False,
        blank=False,
        verbose_name="Gender",
    )

    class Meta:
        ordering = ["-user"]

    @property
    def get_profile_avatar(self):
        if self.profile_avatar:
            return self.profile_avatar.url
        else:
            return "/static/images/profiles/default_avatar.png"

    @property
    def get_user_username(self):
        return self.user.email.split("@")[0].capitalize()

    def __str__(self):
        return self.get_user_username

MyEventWorld/common_stuff/models.py
import uuid

from django.db import models
from django.core.validators import MinLengthValidator

from MyEventWorld.accounts.models import EventProfile


class Interest(models.Model):
    TITLE_MIN_LEN = 2
    TITLE_MAX_LEN = 30
    TITLE_LEN_MESSAGE = f"Title must be at least {TITLE_MIN_LEN} characters long"

    DESCRIPTION_MIN_LEN = 2
    DESCRIPTION_MAX_LEN = 2500
    DESCRIPTION_LEN_MESSAGE = (
        f"Description must be at least {DESCRIPTION_MIN_LEN} characters long"
    )

    interest_creator = models.ForeignKey(
        EventProfile,
        on_delete=models.CASCADE,
        null=False,
        blank=False,
        verbose_name="Interest creator",
    )
    title = models.CharField(
        max_length=TITLE_MAX_LEN,
        validators=(MinLengthValidator(TITLE_MIN_LEN, TITLE_LEN_MESSAGE),),
        null=False,
        blank=False,
        verbose_name="Interest title",
    )
    description = models.TextField(
        max_length=DESCRIPTION_MAX_LEN,
        validators=(MinLengthValidator(DESCRIPTION_MIN_LEN, DESCRIPTION_LEN_MESSAGE),),
        null=True,
        blank=True,
        verbose_name="Interest description",
    )
    id = models.UUIDField(
        default=uuid.uuid4, primary_key=True, unique=True, editable=False
    )

    def __str__(self):
        return self.title


class Message(models.Model):
    TOPIC_MIN_LEN = 2
    TOPIC_MAX_LEN = 200
    TOPIC_LEN_MESSAGE = f"Topic must contain at least {TOPIC_MIN_LEN} characters"

    TEXT_MIN_LEN = 2
    TEXT_MAX_LEN = 2500
    TEXT_LEN_MESSAGE = f"Field must contain at least {TEXT_MIN_LEN} characters"

    sender = models.ForeignKey(
        EventProfile,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name="Message sender",
    )
    receiver = models.ForeignKey(
        EventProfile,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="messages",
        verbose_name="Message receiver",
    )

    topic = models.CharField(
        max_length=TOPIC_MAX_LEN,
        validators=(MinLengthValidator(TOPIC_MIN_LEN, message=TOPIC_LEN_MESSAGE),),
        null=False,
        blank=False,
        verbose_name="Message topic",
    )
    message_text = models.TextField(
        max_length=TEXT_MAX_LEN,
        validators=(MinLengthValidator(TEXT_MIN_LEN, message=TEXT_LEN_MESSAGE),),
        null=False,
        blank=False,
        verbose_name="Message text",
    )
    read = models.BooleanField(default=False, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, primary_key=True, unique=True, editable=False
    )

    def __str__(self):
        return self.topic

    class Meta:
        ordering = ["read", "-date_created"]

MyEventWorld/accounts/forms.py
from django.contrib.auth import get_user_model, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator
from django.forms import ModelForm

from MyEventWorld.core.helpers.gender_types import Genders

from MyEventWorld.accounts.models import EventProfile
from MyEventWorld.core.mixins.form_fields_mixin import DisabledFieldsMixin

UserModel = get_user_model()


class ProfileCreationForm(UserCreationForm):
    AGE_MIN_VALUE = 18
    AGE_MAX_VALUE = 122
    AGE_VALIDATION_MESSAGE = f"Age must be between {AGE_MIN_VALUE} and {AGE_MAX_VALUE}!"

    age = forms.IntegerField(
        validators=(
            MinValueValidator(AGE_MIN_VALUE, message=AGE_VALIDATION_MESSAGE),
            MaxValueValidator(AGE_MAX_VALUE, message=AGE_VALIDATION_MESSAGE),
        )
    )

    error_messages = {
        "password_mismatch": "Password confirmation does not match",
    }

    gender = forms.CharField(
        widget=forms.RadioSelect(choices=Genders.choices()),
        initial=Genders.Unpicked.name,
        required=True,
    )

    class Meta:
        model = UserModel
        fields = (UserModel.USERNAME_FIELD,)

    def clean_email(self):
        data = self.cleaned_data["email"]
        return data.lower()

    def save(self, commit=True):
        user = super().save(commit=commit)

        profile = EventProfile(
            age=self.cleaned_data["age"],
            gender=self.cleaned_data["gender"],
            user=user,
        )
        if commit:
            profile.save()

        return user


class ProfileEditForm(ModelForm):
    gender = forms.CharField(
        widget=forms.RadioSelect(choices=Genders.choices()),
        initial=Genders.Unpicked.name,
        required=True,
    )

    class Meta:
        model = EventProfile
        exclude = ("user",)


class ProfileDeleteForm(DisabledFieldsMixin, ModelForm):
    class Meta:
        model = EventProfile
        fields = "__all__"


class UserLoginForm(AuthenticationForm):
    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username and password:
            if not UserModel.objects.filter(email=username):
                raise forms.ValidationError("Username is not valid")

            user = authenticate(username=username, password=password)

            if not user:
                raise forms.ValidationError("Password is incorrect")

        return super().clean()

MyEventWorld/accounts/views.py
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)
from django.contrib import messages

from MyEventWorld.accounts.mixins.account_mixins import UserOwnershipMixin
from MyEventWorld.accounts.mixins.login_restrict_mixin import NotLoginRequiredMixin

from MyEventWorld.accounts.forms import (
    ProfileCreationForm,
    ProfileEditForm,
    ProfileDeleteForm,
    UserLoginForm,
)
from MyEventWorld.accounts.models import EventProfile
from MyEventWorld.core.mixins.context_mixin import ContextMixin


class UsersList(ListView):
    model = EventProfile
    context_object_name = "profiles"
    template_name = "accounts/event_creators.html"
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get("search", None)

        if query:
            queryset = EventProfile.objects.distinct().filter(
                Q(user__email__icontains=query)
                | Q(first_name__icontains=query)
                | Q(last_name__icontains=query)
                | Q(gender__icontains=query)
                | Q(location__icontains=query)
                | Q(about_me__icontains=query)
                | Q(interest__title__icontains=query)
            )
        return queryset


class UserDetails(ContextMixin, DetailView):
    model = EventProfile
    template_name = "accounts/profile_details.html"


class UserProfile(LoginRequiredMixin, UserOwnershipMixin, ContextMixin, DetailView):
    model = EventProfile
    template_name = "accounts/profile.html"


class UserCreate(NotLoginRequiredMixin, CreateView):
    template_name = "accounts/login_register.html"
    form_class = ProfileCreationForm

    def form_valid(self, form):
        result = super().form_valid(form)
        login(self.request, self.object)
        messages.error(
            self.request,
            "Welcome! Manage your profile from MyProfile",
        )
        return result

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page"] = "register"
        return context

    def get_success_url(self):
        return reverse_lazy("events-list")


class UserProfileEdit(LoginRequiredMixin, UserOwnershipMixin, UpdateView):
    model = EventProfile
    form_class = ProfileEditForm
    template_name = "accounts/profile_edit.html"

    def get_success_url(self):
        return reverse_lazy(
            "profile-details",
            kwargs={
                "pk": self.request.user.pk,
            },
        )


class UserProfileDelete(LoginRequiredMixin, UserOwnershipMixin, DeleteView):
    model = EventProfile
    form_class = ProfileDeleteForm
    template_name = "accounts/profile_delete.html"

    def get_success_url(self):
        messages.success(self.request, "Profile was deleted successfully")
        return reverse_lazy("login")


class UserLogin(NotLoginRequiredMixin, LoginView):
    template_name = "accounts/login_register.html"
    form_class = UserLoginForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page"] = "login"
        return context

    def get_success_url(self):
        return reverse_lazy("events-list")


class UserLogout(LogoutView):
    def get_success_url(self):
        return reverse_lazy("login")


class UserPasswordReset(PasswordResetView):
    template_name = "reset_password.html"


class UserPasswordResetDone(PasswordResetDoneView):
    template_name = "reset_password_sent.html"


class UserPasswordConfirmation(PasswordResetConfirmView):
    template_name = "reset_confirmation.html"


class UserPasswordResetComplete(PasswordResetCompleteView):
    template_name = "reset_password_complete.html"

MyEventWorld/accounts/templates/accounts/event_creators.html
{% extends "common_stuff/base.html" %}

{% block content %}
    <section class="section-center">
        <div class="section-title">
            <h2><span>connect with event creators</span> from around the world</h2>
        </div>
        <div class="search-section">
            <form class="form" action="{% url "users-list" %}" method="get">
                <div class="form-field">
                    <label for="form-search">Search By Event Creator </label>
                    <input class="text-input" id="form-search" type="text" name="search"
                           placeholder="Search by Creator"/>
                </div>
                <input class="search-input" type="submit" value="Search"/>
            </form>
        </div>
        <div class="section-center creators-center">
            {% for profile in profiles %}
                <div class="creator-card">
                    <img class="creator-avatar img" src="{{ profile.get_profile_avatar }}"
                         alt="Profile Avatar"/>
                    <a href="{% url "user-details" profile.pk %}">
                        <div class="creator-profile">
                            <div class="creator-info">
                                <h4 class="nick-name">{{ profile.get_user_username }}</h4>
                                <h4>{% if profile.first_name %}
                                    {{ profile.first_name }}
                                {% endif %}
                                    {% if profile.last_name %}
                                        {{ profile.last_name }}
                                    {% endif %}
                                </h4>
                                <h5>
                                    {{ profile.gender }}
                                </h5>
                                <h5>
                                    {% if profile.age %}
                                        {{ profile.age }} years old
                                    {% endif %}
                                </h5>
                                <h5>
                                    {% if profile.location %}
                                        {{ profile.location }}
                                    {% else %}
                                    {% endif %}
                                </h5>
                            </div>
                        </div>
                        <div class="creator-interests">
                         <h4 class="nick-name">Interests</h4>
                            {% for interest in profile.interest_set.all %}
                                {% if interest %}
                                <h5>
                                    {{ interest }}
                                </h5>
                                {% endif %}
                                {% empty %}
                                <h5>No Interests added</h5>
                            {% endfor %}
                        </div>
                    </a>
                </div>
            {% empty %}
                <div class="search-info">
                    <h1>There is no matches for your search</h1>
                </div>
            {% endfor %}
        </div>
        {% include "partials/pages_pagination.html" %}
    </section>
{% endblock content %}

MyEventWorld/accounts/templates/accounts/login_register.html
{% extends "common_stuff/base.html" %}
{% load static %}

{% block content %}
    {% if page == "register" %}
        <section class="section-center login-register-section">
            <div class="profile-login-register-card">
                    <a href="/">
                        <img src="{% static "images/calendar.svg" %}" alt="Calendar Logo"/>
                    </a>
                    <h3>Register</h3>
                    <p>Create a new Event Creator account</p>

                <form method="post" action="{% url "register" %}" class="login-register-form" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="register-form-field">
                            <label for="formInput#text">{{ field.label }}</label>
                            {{ field }}
                            {% for error in field.errors %}
                                <div class="alert alert--error log-reg-error">{{ error }}</div>
                            {% endfor %}
                        </div>
                    {% endfor %}

                    <div class="register-form-field">
                        <input class="btn" type="submit" value="Sign  In"/>
                    </div>
                </form>
                <div class="register-form-field">
                    <p>Already have an Account?</p>
                    <a class="btn" href="{% url "login" %}">Log In</a>
                </div>
            </div>
        </section>

    {% else %}

        <section class="section-center  login-register-section">
            <div class="profile-login-register-card">
                    <a href="/">
                        <img src="{% static "images/calendar.svg" %}" alt="Calendar Logo"/>
                    </a>
                    <h3>Account Login</h3>
                    <p>Hello Event Creator, Welcome Back!</p>

                <form method="POST" action="{% url "login" %}" class="login-register-form">
                    {% csrf_token %}
                    {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert--error log-reg-error">{{ error }}</div>
                        {% endfor %}
                    {% endif %}

                    <div class="login-form-field">
                        <label for="formInput#text">Email
                        <input
                                class="input input--text"
                                id="formInput#text"
                                type="text"
                                name="username"
                                placeholder="Enter your email"
                        /></label>
                    </div>

                    <div class="login-form-field">
                        <label for="formInput#password">Password
                        <input
                                class="input input--password"
                                id="formInput#passowrd"
                                type="password"
                                name="password"
                                placeholder="*******"
                        /></label>
                    </div>

                    <div class="login-form-field">
                        <input class="btn" type="submit" value="Log In"/>
                        <a class="btn btn-forgot" href="{% url "reset_password" %}">Forgot Password?</a>
                    </div>
                </form>

                <div class="login-form-field">
                    <p>Don’t have an Account?</p>
                    <a class="btn" href="{% url "register" %}">Sign Up</a>
                </div>
            </div>
        </section>
    {% endif %}
{% endblock content %}

MyEventWorld/accounts/templates/accounts/profile_delete.html
{% extends "common_stuff/base.html" %}

{% block content %}
    <section class="section-center delete-profile-section">
        <div class="edit-card">
            <div class="content-box">
                    <a class="btn back-btn" href="{% url "profile-details" eventprofile.pk %}">Cancel</a>
                    <form class="delete-form" method="post" action="{% url "profile-delete" eventprofile.pk %}"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <h3>Are you sure you want to delete your profile ?</h3>
                        <input class="btn" type="submit" value="Delete Profile"/>
                    </form>
                </div>
        </div>
    </section>
{% endblock content %}

MyEventWorld/accounts/templates/accounts/profile_details.html
{% extends "common_stuff/base.html" %}

{% block content %}
    <section class="section-center profile">
        <div class="card">
            <div class="profile-img">
                <img class="profile-photo"
                     src="{{ eventprofile.get_profile_avatar }}" alt="Profile Image"/>
            </div>
            <div class="profile-info">
                <h2>{{ eventprofile.get_user_username }}</h2>
                {{ eventprofile.gender }}
                <h5>{% if eventprofile.age %}
                    {{ eventprofile.age }} years old<br>
                {% endif %}
                </h5>
                <p>{% if eventprofile.first_name %}
                    {{ eventprofile.first_name }}
                {% endif %}
                    {% if eventprofile.last_name %}
                        {{ eventprofile.last_name }}
                    {% endif %}</p>
                <p>{% if eventprofile.location %}
                    <h4> Based in {{ eventprofile.location }}</h4>
                {% endif %}
                    <a href="{% url "message-create" eventprofile.pk %}" class="btn">Send Message</a>
            </div>
            <div class="profile-about">
                <h2 class="about-title">About Me</h2>
                <p class="about">
                    {% if eventprofile.about_me %}
                        {{ eventprofile.about_me }}
                    {% else %}
                        No additional info added
                    {% endif %}
                </p>
            </div>
            <div class="profile-interests">
                <h3 class="interests-title">Interests</h3>
                {% for interest in all_interests %}
                    <h4>{{ interest }}</h4>
                    <p>{{ interest.description }}</p>
                {% empty %}
                    <p>No Interests added yet</p>
                {% endfor %}
            </div>
        </div>
        <div class="profile-event-title">
            <h3>Events</h3>
        </div>

    </section>>
    <div class="profile-events">
            {% for event in all_events %}
                <div class="profile-event-card">
                    <div class="event-img-container">
                        <a href="{% url "event-details" event.pk %}"><img
                                class="event-img" src="{{ event.get_event_avatar }}"
                                alt="Event image"/></a>

                    </div>
                    <div class="event-info">
                        <div class="event-title">
                            <h4><a href="{% url "event-details" event.pk %}">{{ event.title|truncatechars:15 }}</a>
                            </h4>
                        </div>
                        <div class="event-desc">
                            <p>{{ event.event_description|truncatechars:28 }}</p>
                        </div>
                        <div class="event-footer">
                            <p><span>{{ event.event_category }}</span></p>
                        </div>
                    </div>
                </div>
        {% empty %}
            <p class="no-event">
                This user has no events added yet
            </p>
        {% endfor %}
    </div>
{% endblock content %}

MyEventWorld/accounts/templates/accounts/profiles.html
{% extends "common_stuff/base.html" %}

{% block content %}
    <section class="section">
        <div class="section-title">
            <h2><span>connect with event creators</span> from around the world</h2>
        </div>
        <div class="search-section">
            <div class="search-items">
                <form class="form" action="{% url "users-list" %}" method="get">
                    <div class="form-field">
                        <label for="form-search">Search By Event Creator </label>
                        <input class="text-input" id="form-search" type="text" name="search"
                               placeholder="Search by Event Title"/>
                    </div>
                    <input class="search-input" type="submit" value="Search"/>
                </form>
            </div>
        </div>
        <div class="section-center creators-center">
            {% for profile in profiles %}
                <div class="creator-card">
                    <a href="{% url "user-details" profile.pk %}">
                        <div class="creator-profile">
                            <img class="creator-avatar img" src="{{ profile.get_profile_avatar }}"
                                 alt="Profile Avatar"/>
                            <div class="creator-info">
                                <h4>{{ profile.get_user_username }}</h4>
                                <h4>{% if profile.first_name %}
                                    {{ profile.first_name }}
                                {% endif %}
                                    {% if profile.last_name %}
                                        {{ profile.last_name }}
                                    {% endif %}
                                </h4>
                                <h5>
                                    {{ profile.gender }}
                                </h5>
                                <h5>
                                    {% if profile.age %}
                                        {{ profile.age }} years old
                                    {% endif %}
                                </h5>
                                <h5>
                                    {% if profile.location %}
                                        {{ profile.location }}
                                    {% else %}
                                    {% endif %}
                                </h5>
                            </div>
                        </div>
                        <div class="creator-interests">
                            {% for interest in profile.interest_set.all %}
                                <h5>
                                    {{ interest }}
                                </h5>
                            {% endfor %}

                        </div>
                    </a>
                </div>
            {% empty %}
                <div class="search-info">
                    <h1>There is no matches for your search</h1>
                </div>
            {% endfor %}
        </div>
        {% if is_paginated %}
            <div class="pagination">
            <ul class="container">
            {% if page_obj.has_previous and request.GET.search %}
                <li><a href="{{ request.get_full_path }}&page={{ page_obj.previous_page_number }}"
                       class="btn"
                       data-page="{{ request.get_full_path }}&page={{ page_obj.previous_page_number }}">&#10094;
                    Prev</a></li>
            {% elif page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}" class="btn"
                       data-page="{{ request.get_full_path }}&page={{ page_obj.previous_page_number }}">&#10094;
                    Prev</a></li>
            {% endif %}

            <span class="btn-page">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
            {% if page_obj.has_next and request.GET.search %}
                <li><a href="{{ request.get_full_path }}&page={{ page_obj.next_page_number }}"
                       class="btn"
                       data-page="{{ request.get_full_path }}&page={{ page_obj.next_page_number }}">Next &#10095;</a>
                </li>
            {% elif page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}" class="btn"
                       data-page="?page={{ page_obj.next_page_number }}">Next &#10095;</a></li>
            {% endif %}
        {% endif %}
        </ul>
        </div>
    </section>
{% endblock content %}